authors:
  jdubec:
    name: Jakub Dubec
    description: Cloud Infrastructure Engineer
    avatar: https://gravatar.com/avatar/f86b0b8d2378b9722aff20787b2d5ac093651b3908900d64df152b47eed9889d?s=200
    url: mailto:jdubec@culturepulse.ai
